import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#ccc3d8",
        "on-secondary": "#313030",
        primary: "#d2bbff",
        "secondary-fixed": "#e5e2e1",
        background: "#131313",
        "on-primary-fixed": "#25005a",
        "surface-container-lowest": "#0e0e0e",
        "surface-container": "#1f2020",
        "tertiary-container": "#656767",
        "on-primary-container": "#ede0ff",
        surface: "#131313",
        "on-secondary-fixed-variant": "#474646",
        "surface-bright": "#393939",
        "secondary-fixed-dim": "#c8c6c5",
        "on-surface": "#e4e2e1",
        "error-container": "#93000a",
        "on-background": "#e4e2e1",
        "surface-container-high": "#2a2a2a",
        "primary-fixed": "#eaddff",
        "secondary-container": "#4a4949",
        "on-tertiary-fixed-variant": "#454747",
        "outline-variant": "#4a4455",
        "on-tertiary-container": "#e6e6e6",
        "surface-container-highest": "#353535",
        "inverse-on-surface": "#303030",
        secondary: "#c8c6c5",
        "on-secondary-fixed": "#1c1b1b",
        "surface-dim": "#131313",
        "tertiary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#d2bbff",
        outline: "#958da1",
        "on-secondary-container": "#bab8b7",
        "surface-container-low": "#1b1c1c",
        "surface-tint": "#d2bbff",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary": "#2f3131",
        "inverse-primary": "#732ee4",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e4e2e1",
        error: "#ffb4ab",
        "surface-variant": "#353535",
        "primary-container": "#7c3aed",
        "on-primary-fixed-variant": "#5a00c6",
        tertiary: "#c6c6c7",
        "on-tertiary-fixed": "#1a1c1c",
        "on-primary": "#3f008e",
        "on-error": "#690005",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        margin: "40px",
        "container-max": "1440px",
        gutter: "24px",
      },
      fontFamily: {
        "data-mono": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-playfair-display)", "serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-playfair-display)", "serif"],
        "display-lg": ["var(--font-playfair-display)", "serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-playfair-display)", "serif"],
      },
      fontSize: {
        "data-mono": ["13px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
export default config;
