import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./../styles/globals.css";
import { Header } from "@/components/features/shared/Header";
import { Footer } from "@/components/features/shared/Footer";

const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });
const playfair = Playfair_Display({ subsets: ["latin"], variable: '--font-playfair-display' });

export const metadata: Metadata = {
  title: "HireSignal | Market Intelligence Terminal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
        <head>
            <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet"/>
        </head>
      <body className={`${inter.variable} ${playfair.variable} bg-background text-on-surface selection:bg-primary selection:text-on-primary`}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
